name: insar-smoothness-env
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - appnope=0.1.4=py311hecd8cb5_0
  - asttokens=3.0.0=py311hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h9b7fc35_0
  - brotli-python=1.0.9=py311h6d0c2b6_9
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - comm=0.2.1=py311hecd8cb5_0
  - contourpy=1.3.1=py311h1962661_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h6c40b1e_0
  - debugpy=1.8.11=py311h6d0c2b6_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6d0c2b6_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py311h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gettext=0.21.0=h4e8c18a_2
  - graphite2=1.3.14=he9d5cce_1
  - harfbuzz=10.2.0=h060d35a_1
  - icu=73.1=hcec6c5f_0
  - intel-openmp=2023.1.0=ha357a0b_43548
  - ipykernel=6.29.5=py311hecd8cb5_1
  - ipython=8.15.0=py311hecd8cb5_0
  - jedi=0.19.2=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - jupyter_client=8.6.3=py311hecd8cb5_0
  - jupyter_core=5.8.1=py311hecd8cb5_0
  - kiwisolver=1.4.8=py311h6d0c2b6_0
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libffi=3.4.4=hecd8cb5_1
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - matplotlib=3.10.0=py311hecd8cb5_0
  - matplotlib-base=3.10.0=py311h919b35b_0
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - mkl=2023.1.0=h8e150cf_43560
  - mkl-service=2.4.0=py311h46256e1_2
  - mkl_fft=1.3.8=py311h6c40b1e_0
  - mkl_random=1.2.4=py311ha357a0b_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=py311hecd8cb5_0
  - numexpr=2.14.1=py311heeb4c95_1
  - numpy=1.26.4=py311h728a8a3_0
  - numpy-base=1.26.4=py311h53bf9ac_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.0.17=hee2dfae_0
  - packaging=25.0=py311hecd8cb5_0
  - pandas=2.3.1=py311hebe84f7_0
  - parso=0.8.4=py311hecd8cb5_0
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=py311hecd8cb5_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.3.0=py311h25d8182_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - platformdirs=4.3.7=py311hecd8cb5_0
  - prompt-toolkit=3.0.43=py311hecd8cb5_0
  - psutil=5.9.0=py311h46256e1_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py311hecd8cb5_0
  - pyparsing=3.2.0=py311hecd8cb5_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0post0=py311hecd8cb5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=py311hecd8cb5_0
  - pyzmq=26.2.0=py311h6d0c2b6_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=py311hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.1=py311h46256e1_0
  - traitlets=5.14.3=py311hecd8cb5_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py311h46256e1_1
  - wcwidth=0.2.13=py311hecd8cb5_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=hcec6c5f_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
